version: "3.7"


services:
    app:
        build: .
        container_name: music-proj-app
        ports: 
          - "5000:5000"
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_NAME}
          - POSTGRES_HOST=db
          - POSTRES_PORT=5432
        networks:
          - postgres-network
    db:
        image: postgres
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_NAME}
        ports:
          - "5432:5432"
        volumes:
          - ./db-scripts:/docker-entrypoint-initdb.d/
        networks:
          - postgres-network
    pgadmin:
        image: thajeztah/pgadmin4
        ports:
          - "9000:5050"
        depends_on:
          - db
        networks:
          - postgres-network
networks:
    postgres-network:
        driver: bridge
