import os

POSTGRES_USER = os.getenv("POSTGRES_USER", "postgres")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "postgres")
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", 5432)
POSTGRES_NAME = os.getenv("POSTGRES_NAME", "postgres")
DB_CONNECTION = f"postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_NAME}"


CONFIG = dict(
    SQLALCHEMY_DATABASE_URI=DB_CONNECTION, SQLALCHEMY_TRACK_MODIFICATIONS=False
)
